spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/layim
    username: root
    password: root
  http:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
debug: false

layim.websocket:
    ip: 10.16.2.21
    port: 8888
    heartBeatTimeout: 0
layim.upload.dir: E:\other\SpringBootLayIM\upload